<div class="alert alert-block alert-info">
     <b>AI LAB Project</b>
     <br>
Name: Eesha Noor
<br>
RollNumber: BSAI-S25-001
</div>

<div class="alert alert-block alert-success">
<br>Project Name:</br>
Predict smartphone prices based on technical specifications using a Random Forest regression
</div>

<div class="alert alert-block alert-info">
 Import Required Libraries   <br>
 import pandas as pd (pandas)<br>
 from sklearn.preprocessing import LabelEncoder and import joblib (sklearn.preprocessing, joblib)<br>
from sklearn.model_selection import train_test_split (sklearn.model_selection)<br>
 from sklearn.ensemble import RandomForestRegressor (sklearn.ensemble)<br>
 from sklearn.metrics import mean_absolute_error, r2_score (sklearn.metrics)<br>
</div>

<div class="alert alert-block alert-info">
    <b> Steps</b> <br>
    1. Data Reading / Data Loading <br>
    2. Data Exploration <br>
    3. Data Pre-Processing <br>
    4. Train-Test Splitting <br>
    5. Model Application <br>
    6. Model Accuracy <br>
    7. Application Phase <br>
</div>

<div class="alert alert-block alert-info">
 Loading and reading the Dataset
 </div>

In [1]:
import pandas as pd
data=pd.read_csv("smartphone_dataset_1lacc.csv")
data

,brand,model_name,os,price_inr,launch_year,5g_support,dual_sim,expandable_storage,water_resistance,wireless_charging,...,storage_gb,thickness_mm,display_type,refresh_rate_hz,battery_mah,fast_charging_w,rear_camera_mp,front_camera_mp,camera_setup,weight_g
0,Google,Google_2528,Android,71511,2020,1,1,0,0,1,...,128,8.29,AMOLED,120,4657,25,200,16,Wide,175.2
1,Samsung,Samsung_9006,Android,57511,2018,1,0,1,0,0,...,64,7.41,LCD,120,3817,65,50,8,"Telephoto, Wide",175.6
2,Google,Google_2059,Android,76042,2022,0,1,1,1,0,...,128,8.89,LCD,90,5069,25,200,32,"Wide, Ultra-Wide",184.0
3,Realme,Realme_5737,Android,26916,2021,0,1,0,1,0,...,64,7.67,AMOLED,60,4323,45,50,8,"Macro, Wide, Telephoto, Depth",173.6
4,OnePlus,OnePlus_5548,Android,31505,2022,1,0,0,0,1,...,256,9.41,AMOLED,60,6497,25,50,16,"Depth, Macro, Telephoto, Wide",197.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100105,Realme,Realme_6377,Android,19183,2019,1,0,0,0,0,...,128,9.34,OLED,120,3935,65,48,16,"Ultra-Wide, Wide",197.4
100106,Nothing,Nothing_4957,Android,46470,2025,1,1,0,0,1,...,128,8.79,OLED,60,6200,33,108,16,Depth,236.0
100107,Nothing,Nothing_7441,Android,29289,2019,1,1,1,0,0,...,128,8.80,OLED,144,5675,33,108,8,"Depth, Ultra-Wide",190.8
100108,Oppo,Oppo_1179,Android,48719,2023,1,1,1,0,0,...,64,8.55,LCD,60,4247,18,50,16,"Macro, Telephoto",202.7
100109,Realme,Realme_8186,Android,26737,2021,0,1,0,0,1,...,64,9.27,AMOLED,60,3657,33,50,32,Wide,187.5

<div class="alert alert-block alert-info">
Droping Unnecessary Features
</div>

In [2]:
data.drop('gpu_score', axis=1, inplace=True)
data.drop('cpu_score', axis=1, inplace=True)
data.drop('screen_to_body_ratio', axis=1, inplace=True)
data.drop('colors_available', axis=1, inplace=True)
data.drop('bluetooth_version', axis=1, inplace=True)
data.drop('wifi_version', axis=1, inplace=True)
data.drop('chipset', axis=1, inplace=True)
data.drop('refresh_rate_hz', axis=1, inplace=True)
data.drop('battery_mah', axis=1, inplace=True)
data.drop('camera_setup', axis=1, inplace=True)
data.drop('weight_g', axis=1, inplace=True)
data.drop('thickness_mm', axis=1, inplace=True)

<div class="alert alert-block alert-info">
Verify Cleaned Data
</div>

In [3]:
data.head()

,brand,model_name,os,price_inr,launch_year,5g_support,dual_sim,expandable_storage,water_resistance,wireless_charging,fingerprint_sensor,face_unlock,build_material,warranty_years,ram_gb,storage_gb,display_type,fast_charging_w,rear_camera_mp,front_camera_mp
0,Google,Google_2528,Android,71511,2020,1,1,0,0,1,1,1,Metal,1,12,128,AMOLED,25,200,16
1,Samsung,Samsung_9006,Android,57511,2018,1,0,1,0,0,1,1,Metal,2,16,64,LCD,65,50,8
2,Google,Google_2059,Android,76042,2022,0,1,1,1,0,1,0,Glass,2,16,128,LCD,25,200,32
3,Realme,Realme_5737,Android,26916,2021,0,1,0,1,0,1,1,Metal,1,12,64,AMOLED,45,50,8
4,OnePlus,OnePlus_5548,Android,31505,2022,1,0,0,0,1,1,1,Glass,2,12,256,AMOLED,25,50,16

In [4]:
data.tail()

,brand,model_name,os,price_inr,launch_year,5g_support,dual_sim,expandable_storage,water_resistance,wireless_charging,fingerprint_sensor,face_unlock,build_material,warranty_years,ram_gb,storage_gb,display_type,fast_charging_w,rear_camera_mp,front_camera_mp
100105,Realme,Realme_6377,Android,19183,2019,1,0,0,0,0,1,1,Glass,2,4,128,OLED,65,48,16
100106,Nothing,Nothing_4957,Android,46470,2025,1,1,0,0,1,1,0,Plastic,1,8,128,OLED,33,108,16
100107,Nothing,Nothing_7441,Android,29289,2019,1,1,1,0,0,1,1,Metal,2,12,128,OLED,33,108,8
100108,Oppo,Oppo_1179,Android,48719,2023,1,1,1,0,0,1,1,Metal,1,8,64,LCD,18,50,16
100109,Realme,Realme_8186,Android,26737,2021,0,1,0,0,1,1,1,Glass,2,8,64,AMOLED,33,50,32

In [5]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 100110 entries, 0 to 100109
Data columns (total 20 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   brand               100110 non-null  str
 1   model_name          100110 non-null  str
 2   os                  100110 non-null  str
 3   price_inr           100110 non-null  int64
 4   launch_year         100110 non-null  int64
 5   5g_support          100110 non-null  int64
 6   dual_sim            100110 non-null  int64
 7   expandable_storage  100110 non-null  int64
 8   water_resistance    100110 non-null  int64
 9   wireless_charging   100110 non-null  int64
 10  fingerprint_sensor  100110 non-null  int64
 11  face_unlock         100110 non-null  int64
 12  build_material      100110 non-null  str
 13  warranty_years      100110 non-null  int64
 14  ram_gb              100110 non-null  int64
 15  storage_gb          100110 non-null  int64
 16  display_type        100110 non-null  str
 17  fast_charging_w     100110 non-null  int64
 18  rear_camera_mp      100110 non-null  int64
 19  front_camera_mp     100110 non-null  int64
dtypes: int64(15), str(5)
memory usage: 18.5 MB

In [6]:
# Missing values check
data.isnull().sum()

brand                 0
model_name            0
os                    0
price_inr             0
launch_year           0
5g_support            0
dual_sim              0
expandable_storage    0
water_resistance      0
wireless_charging     0
fingerprint_sensor    0
face_unlock           0
build_material        0
warranty_years        0
ram_gb                0
storage_gb            0
display_type          0
fast_charging_w       0
rear_camera_mp        0
front_camera_mp       0
dtype: int64

<div class="alert alert-block alert-info">
Encode Categorical Variables
</div>

In [7]:
from sklearn.preprocessing import LabelEncoder
import joblib

# Text columns
text_columns = ['brand', 'model_name', 'os', 'build_material', 'display_type']

# Dictionary to store encoders
encoders = {}

# Encoding
for col in text_columns:
    le = LabelEncoder()
    data[col] = le.fit_transform(data[col])
    encoders[col] = le

# Save encoders
joblib.dump(encoders, "encoders.pkl")

print("Encoding completed")

Encoding completed

 <div class="alert alert-block alert-info">
 Save Encoded Dataset 
 </div>

In [8]:
data.to_csv("encoded_mobile_data.csv", index=False)

In [9]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 100110 entries, 0 to 100109
Data columns (total 20 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   brand               100110 non-null  int64
 1   model_name          100110 non-null  int64
 2   os                  100110 non-null  int64
 3   price_inr           100110 non-null  int64
 4   launch_year         100110 non-null  int64
 5   5g_support          100110 non-null  int64
 6   dual_sim            100110 non-null  int64
 7   expandable_storage  100110 non-null  int64
 8   water_resistance    100110 non-null  int64
 9   wireless_charging   100110 non-null  int64
 10  fingerprint_sensor  100110 non-null  int64
 11  face_unlock         100110 non-null  int64
 12  build_material      100110 non-null  int64
 13  warranty_years      100110 non-null  int64
 14  ram_gb              100110 non-null  int64
 15  storage_gb          100110 non-null  int64
 16  display_type        100110 non-null  int64
 17  fast_charging_w     100110 non-null  int64
 18  rear_camera_mp      100110 non-null  int64
 19  front_camera_mp     100110 non-null  int64
dtypes: int64(20)
memory usage: 15.3 MB

<div class="alert alert-block alert-info">
Define Features (X) and Target (y)
</div>

In [10]:
X = data.drop('price_inr', axis=1)
y = data['price_inr']

<div class="alert alert-block alert-info">
Split Data into Training and Testing Sets
<div>

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

<div class="alert alert-block alert-info">
Train a Random Forest Regressor
</div>

In [12]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()

model.fit(X_train, y_train)

RandomForestRegressor()

<div class="alert alert-block alert-info">
Save the Trained Model
</div>

In [13]:
import joblib

joblib.dump(model, "mobile_price_model.pkl")

print("Model Saved Successfully")

Model Saved Successfully

<div class="alert alert-block alert-info">
Load the Saved Model
</div>

In [14]:
loaded_model = joblib.load("mobile_price_model.pkl")

print("Model Loaded Successfully")

Model Loaded Successfully

<div class="alert alert-block alert-info">
Predictions on the Test Set
</div>

In [15]:
predictions = model.predict(X_test)

print(predictions[:10])

[14727.04 41080.21 35788.6  90789.76 64134.81 27593.4  13798.78 26077.15
 26682.81 35847.58]

<div class="alert alert-block alert-info">
Evaluate Model Performance
</div>

In [16]:
from sklearn.metrics import mean_absolute_error, r2_score

mae = mean_absolute_error(y_test, predictions)
r2 = r2_score(y_test, predictions)

print("MAE:", mae)
print("R2 Score:", r2)

MAE: 7065.141397962243
R2 Score: 0.8520149440403503