Read CSV:

In [3]:
import pandas as pd
Dataset = pd.read_csv('smartphone_dataset_1lacc.csv')
Dataset

,brand,model_name,os,price_inr,launch_year,5g_support,dual_sim,expandable_storage,water_resistance,wireless_charging,...,storage_gb,thickness_mm,display_type,refresh_rate_hz,battery_mah,fast_charging_w,rear_camera_mp,front_camera_mp,camera_setup,weight_g
0,Google,Google_2528,Android,71511,2020,1,1,0,0,1,...,128,8.29,AMOLED,120,4657,25,200,16,Wide,175.2
1,Samsung,Samsung_9006,Android,57511,2018,1,0,1,0,0,...,64,7.41,LCD,120,3817,65,50,8,"Telephoto, Wide",175.6
2,Google,Google_2059,Android,76042,2022,0,1,1,1,0,...,128,8.89,LCD,90,5069,25,200,32,"Wide, Ultra-Wide",184.0
3,Realme,Realme_5737,Android,26916,2021,0,1,0,1,0,...,64,7.67,AMOLED,60,4323,45,50,8,"Macro, Wide, Telephoto, Depth",173.6
4,OnePlus,OnePlus_5548,Android,31505,2022,1,0,0,0,1,...,256,9.41,AMOLED,60,6497,25,50,16,"Depth, Macro, Telephoto, Wide",197.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100105,Realme,Realme_6377,Android,19183,2019,1,0,0,0,0,...,128,9.34,OLED,120,3935,65,48,16,"Ultra-Wide, Wide",197.4
100106,Nothing,Nothing_4957,Android,46470,2025,1,1,0,0,1,...,128,8.79,OLED,60,6200,33,108,16,Depth,236.0
100107,Nothing,Nothing_7441,Android,29289,2019,1,1,1,0,0,...,128,8.80,OLED,144,5675,33,108,8,"Depth, Ultra-Wide",190.8
100108,Oppo,Oppo_1179,Android,48719,2023,1,1,1,0,0,...,64,8.55,LCD,60,4247,18,50,16,"Macro, Telephoto",202.7
100109,Realme,Realme_8186,Android,26737,2021,0,1,0,0,1,...,64,9.27,AMOLED,60,3657,33,50,32,Wide,187.5

Print Top 5 rows of dataset:

In [4]:
Dataset.head()

,brand,model_name,os,price_inr,launch_year,5g_support,dual_sim,expandable_storage,water_resistance,wireless_charging,...,storage_gb,thickness_mm,display_type,refresh_rate_hz,battery_mah,fast_charging_w,rear_camera_mp,front_camera_mp,camera_setup,weight_g
0,Google,Google_2528,Android,71511,2020,1,1,0,0,1,...,128,8.29,AMOLED,120,4657,25,200,16,Wide,175.2
1,Samsung,Samsung_9006,Android,57511,2018,1,0,1,0,0,...,64,7.41,LCD,120,3817,65,50,8,"Telephoto, Wide",175.6
2,Google,Google_2059,Android,76042,2022,0,1,1,1,0,...,128,8.89,LCD,90,5069,25,200,32,"Wide, Ultra-Wide",184.0
3,Realme,Realme_5737,Android,26916,2021,0,1,0,1,0,...,64,7.67,AMOLED,60,4323,45,50,8,"Macro, Wide, Telephoto, Depth",173.6
4,OnePlus,OnePlus_5548,Android,31505,2022,1,0,0,0,1,...,256,9.41,AMOLED,60,6497,25,50,16,"Depth, Macro, Telephoto, Wide",197.9

Print Bottom 5 rows of dataset

In [5]:
Dataset.tail()

,brand,model_name,os,price_inr,launch_year,5g_support,dual_sim,expandable_storage,water_resistance,wireless_charging,...,storage_gb,thickness_mm,display_type,refresh_rate_hz,battery_mah,fast_charging_w,rear_camera_mp,front_camera_mp,camera_setup,weight_g
100105,Realme,Realme_6377,Android,19183,2019,1,0,0,0,0,...,128,9.34,OLED,120,3935,65,48,16,"Ultra-Wide, Wide",197.4
100106,Nothing,Nothing_4957,Android,46470,2025,1,1,0,0,1,...,128,8.79,OLED,60,6200,33,108,16,Depth,236.0
100107,Nothing,Nothing_7441,Android,29289,2019,1,1,1,0,0,...,128,8.80,OLED,144,5675,33,108,8,"Depth, Ultra-Wide",190.8
100108,Oppo,Oppo_1179,Android,48719,2023,1,1,1,0,0,...,64,8.55,LCD,60,4247,18,50,16,"Macro, Telephoto",202.7
100109,Realme,Realme_8186,Android,26737,2021,0,1,0,0,1,...,64,9.27,AMOLED,60,3657,33,50,32,Wide,187.5

Print Number of Rows and Columns in dataset:

In [7]:
print('rows: ', Dataset.shape[0])
print('columns: ', Dataset.shape[1])

rows:  100110
columns:  32

Print/Determine all the null columns in dataset:

In [8]:
Dataset.isnull().sum()

brand                   0
model_name              0
os                      0
price_inr               0
launch_year             0
5g_support              0
dual_sim                0
expandable_storage      0
water_resistance        0
wireless_charging       0
fingerprint_sensor      0
face_unlock             0
gpu_score               0
cpu_score               0
screen_to_body_ratio    0
build_material          0
colors_available        0
warranty_years          0
bluetooth_version       0
wifi_version            0
chipset                 0
ram_gb                  0
storage_gb              0
thickness_mm            0
display_type            0
refresh_rate_hz         0
battery_mah             0
fast_charging_w         0
rear_camera_mp          0
front_camera_mp         0
camera_setup            0
weight_g                0
dtype: int64

Filling null values using mean / median / mode:
Dataset = Dataset.fillna(Dataset.mean)
Dataset = Dataset.fillna(Dataset.median)
Dataset = Dataset.fillna(Dataset.mode)
since there is no null value so i don't use it

Print datatype of each column

In [11]:
print(Dataset.dtypes)

brand                       str
model_name                  str
os                          str
price_inr                 int64
launch_year               int64
5g_support                int64
dual_sim                  int64
expandable_storage        int64
water_resistance          int64
wireless_charging         int64
fingerprint_sensor        int64
face_unlock               int64
gpu_score                 int64
cpu_score                 int64
screen_to_body_ratio    float64
build_material              str
colors_available          int64
warranty_years            int64
bluetooth_version       float64
wifi_version                str
chipset                     str
ram_gb                    int64
storage_gb                int64
thickness_mm            float64
display_type                str
refresh_rate_hz           int64
battery_mah               int64
fast_charging_w           int64
rear_camera_mp            int64
front_camera_mp           int64
camera_setup                str
weight_g                float64
dtype: object