Read CSV:

In [20]:
import pandas as pd
Dataset = pd.read_csv('smartphone_dataset_1lacc.csv')
Dataset

,brand,model_name,os,price_inr,launch_year,5g_support,dual_sim,expandable_storage,water_resistance,wireless_charging,...,storage_gb,thickness_mm,display_type,refresh_rate_hz,battery_mah,fast_charging_w,rear_camera_mp,front_camera_mp,camera_setup,weight_g
0,Google,Google_2528,Android,71511,2020,1,1,0,0,1,...,128,8.29,AMOLED,120,4657,25,200,16,Wide,175.2
1,Samsung,Samsung_9006,Android,57511,2018,1,0,1,0,0,...,64,7.41,LCD,120,3817,65,50,8,"Telephoto, Wide",175.6
2,Google,Google_2059,Android,76042,2022,0,1,1,1,0,...,128,8.89,LCD,90,5069,25,200,32,"Wide, Ultra-Wide",184.0
3,Realme,Realme_5737,Android,26916,2021,0,1,0,1,0,...,64,7.67,AMOLED,60,4323,45,50,8,"Macro, Wide, Telephoto, Depth",173.6
4,OnePlus,OnePlus_5548,Android,31505,2022,1,0,0,0,1,...,256,9.41,AMOLED,60,6497,25,50,16,"Depth, Macro, Telephoto, Wide",197.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100105,Realme,Realme_6377,Android,19183,2019,1,0,0,0,0,...,128,9.34,OLED,120,3935,65,48,16,"Ultra-Wide, Wide",197.4
100106,Nothing,Nothing_4957,Android,46470,2025,1,1,0,0,1,...,128,8.79,OLED,60,6200,33,108,16,Depth,236.0
100107,Nothing,Nothing_7441,Android,29289,2019,1,1,1,0,0,...,128,8.80,OLED,144,5675,33,108,8,"Depth, Ultra-Wide",190.8
100108,Oppo,Oppo_1179,Android,48719,2023,1,1,1,0,0,...,64,8.55,LCD,60,4247,18,50,16,"Macro, Telephoto",202.7
100109,Realme,Realme_8186,Android,26737,2021,0,1,0,0,1,...,64,9.27,AMOLED,60,3657,33,50,32,Wide,187.5

Print Top 5 rows of dataset:

In [21]:
Dataset.head()

,brand,model_name,os,price_inr,launch_year,5g_support,dual_sim,expandable_storage,water_resistance,wireless_charging,...,storage_gb,thickness_mm,display_type,refresh_rate_hz,battery_mah,fast_charging_w,rear_camera_mp,front_camera_mp,camera_setup,weight_g
0,Google,Google_2528,Android,71511,2020,1,1,0,0,1,...,128,8.29,AMOLED,120,4657,25,200,16,Wide,175.2
1,Samsung,Samsung_9006,Android,57511,2018,1,0,1,0,0,...,64,7.41,LCD,120,3817,65,50,8,"Telephoto, Wide",175.6
2,Google,Google_2059,Android,76042,2022,0,1,1,1,0,...,128,8.89,LCD,90,5069,25,200,32,"Wide, Ultra-Wide",184.0
3,Realme,Realme_5737,Android,26916,2021,0,1,0,1,0,...,64,7.67,AMOLED,60,4323,45,50,8,"Macro, Wide, Telephoto, Depth",173.6
4,OnePlus,OnePlus_5548,Android,31505,2022,1,0,0,0,1,...,256,9.41,AMOLED,60,6497,25,50,16,"Depth, Macro, Telephoto, Wide",197.9

Print Bottom 5 rows of dataset

In [22]:
Dataset.tail()

,brand,model_name,os,price_inr,launch_year,5g_support,dual_sim,expandable_storage,water_resistance,wireless_charging,...,storage_gb,thickness_mm,display_type,refresh_rate_hz,battery_mah,fast_charging_w,rear_camera_mp,front_camera_mp,camera_setup,weight_g
100105,Realme,Realme_6377,Android,19183,2019,1,0,0,0,0,...,128,9.34,OLED,120,3935,65,48,16,"Ultra-Wide, Wide",197.4
100106,Nothing,Nothing_4957,Android,46470,2025,1,1,0,0,1,...,128,8.79,OLED,60,6200,33,108,16,Depth,236.0
100107,Nothing,Nothing_7441,Android,29289,2019,1,1,1,0,0,...,128,8.80,OLED,144,5675,33,108,8,"Depth, Ultra-Wide",190.8
100108,Oppo,Oppo_1179,Android,48719,2023,1,1,1,0,0,...,64,8.55,LCD,60,4247,18,50,16,"Macro, Telephoto",202.7
100109,Realme,Realme_8186,Android,26737,2021,0,1,0,0,1,...,64,9.27,AMOLED,60,3657,33,50,32,Wide,187.5

Print Number of Rows and Columns in dataset:

In [23]:
print('rows: ', Dataset.shape[0])
print('columns: ', Dataset.shape[1])

rows:  100110
columns:  32

Print/Determine all the null columns in dataset:

In [24]:
Dataset.isnull().sum()

brand                   0
model_name              0
os                      0
price_inr               0
launch_year             0
5g_support              0
dual_sim                0
expandable_storage      0
water_resistance        0
wireless_charging       0
fingerprint_sensor      0
face_unlock             0
gpu_score               0
cpu_score               0
screen_to_body_ratio    0
build_material          0
colors_available        0
warranty_years          0
bluetooth_version       0
wifi_version            0
chipset                 0
ram_gb                  0
storage_gb              0
thickness_mm            0
display_type            0
refresh_rate_hz         0
battery_mah             0
fast_charging_w         0
rear_camera_mp          0
front_camera_mp         0
camera_setup            0
weight_g                0
dtype: int64

Filling null values using mean / median / mode:
Dataset = Dataset.fillna(Dataset.mean)
Dataset = Dataset.fillna(Dataset.median)
Dataset = Dataset.fillna(Dataset.mode)
since there is no null value so i don't use it

Print datatype of each column

In [25]:
print(Dataset.dtypes)

brand                       str
model_name                  str
os                          str
price_inr                 int64
launch_year               int64
5g_support                int64
dual_sim                  int64
expandable_storage        int64
water_resistance          int64
wireless_charging         int64
fingerprint_sensor        int64
face_unlock               int64
gpu_score                 int64
cpu_score                 int64
screen_to_body_ratio    float64
build_material              str
colors_available          int64
warranty_years            int64
bluetooth_version       float64
wifi_version                str
chipset                     str
ram_gb                    int64
storage_gb                int64
thickness_mm            float64
display_type                str
refresh_rate_hz           int64
battery_mah               int64
fast_charging_w           int64
rear_camera_mp            int64
front_camera_mp           int64
camera_setup                str
weight_g                float64
dtype: object

Checking unique values of specific column

In [26]:
Dataset['price_inr'].unique()

array([71511, 57511, 76042, ..., 43021, 27566, 48719], shape=(54716,))

In [27]:
Dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 100110 entries, 0 to 100109
Data columns (total 32 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   brand                 100110 non-null  str
 1   model_name            100110 non-null  str
 2   os                    100110 non-null  str
 3   price_inr             100110 non-null  int64
 4   launch_year           100110 non-null  int64
 5   5g_support            100110 non-null  int64
 6   dual_sim              100110 non-null  int64
 7   expandable_storage    100110 non-null  int64
 8   water_resistance      100110 non-null  int64
 9   wireless_charging     100110 non-null  int64
 10  fingerprint_sensor    100110 non-null  int64
 11  face_unlock           100110 non-null  int64
 12  gpu_score             100110 non-null  int64
 13  cpu_score             100110 non-null  int64
 14  screen_to_body_ratio  100110 non-null  float64
 15  build_material        100110 non-null  str
 16  colors_available      100110 non-null  int64
 17  warranty_years        100110 non-null  int64
 18  bluetooth_version     100110 non-null  float64
 19  wifi_version          100110 non-null  str
 20  chipset               100110 non-null  str
 21  ram_gb                100110 non-null  int64
 22  storage_gb            100110 non-null  int64
 23  thickness_mm          100110 non-null  float64
 24  display_type          100110 non-null  str
 25  refresh_rate_hz       100110 non-null  int64
 26  battery_mah           100110 non-null  int64
 27  fast_charging_w       100110 non-null  int64
 28  rear_camera_mp        100110 non-null  int64
 29  front_camera_mp       100110 non-null  int64
 30  camera_setup          100110 non-null  str
 31  weight_g              100110 non-null  float64
dtypes: float64(4), int64(20), str(8)
memory usage: 31.2 MB

 Type conversion to int

In [28]:
Dataset.columns

Index(['brand', 'model_name', 'os', 'price_inr', 'launch_year', '5g_support',
       'dual_sim', 'expandable_storage', 'water_resistance',
       'wireless_charging', 'fingerprint_sensor', 'face_unlock', 'gpu_score',
       'cpu_score', 'screen_to_body_ratio', 'build_material',
       'colors_available', 'warranty_years', 'bluetooth_version',
       'wifi_version', 'chipset', 'ram_gb', 'storage_gb', 'thickness_mm',
       'display_type', 'refresh_rate_hz', 'battery_mah', 'fast_charging_w',
       'rear_camera_mp', 'front_camera_mp', 'camera_setup', 'weight_g'],
      dtype='str')

 Drop unnecessary columns for price prediction

In [29]:
columns_to_drop = ['model_name', 'camera_setup', 'os']
Dataset.drop(columns=columns_to_drop, inplace=True)

 Check datatypes

In [30]:
print(Dataset.dtypes)

brand                       str
price_inr                 int64
launch_year               int64
5g_support                int64
dual_sim                  int64
expandable_storage        int64
water_resistance          int64
wireless_charging         int64
fingerprint_sensor        int64
face_unlock               int64
gpu_score                 int64
cpu_score                 int64
screen_to_body_ratio    float64
build_material              str
colors_available          int64
warranty_years            int64
bluetooth_version       float64
wifi_version                str
chipset                     str
ram_gb                    int64
storage_gb                int64
thickness_mm            float64
display_type                str
refresh_rate_hz           int64
battery_mah               int64
fast_charging_w           int64
rear_camera_mp            int64
front_camera_mp           int64
weight_g                float64
dtype: object

 Split into X (features) and y (target = price_inr)

In [31]:
X = Dataset.drop('price_inr', axis=1)
y = Dataset['price_inr']
print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (100110, 28)
y shape: (100110,)

In [32]:
X = Dataset.drop('price_inr', axis=1)
y = Dataset['price_inr']
print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (100110, 28)
y shape: (100110,)

In [33]:
X = Dataset.drop('price_inr', axis=1)
y = Dataset['price_inr']
print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (100110, 28)
y shape: (100110,)

 Convert object (string) columns to integer codes

In [34]:
cat_columns = X.select_dtypes(['object']).columns
X[cat_columns] = X[cat_columns].apply(lambda x: pd.factorize(x)[0])

C:\Users\hp\AppData\Local\Temp\ipykernel_10388\1288430151.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_columns = X.select_dtypes(['object']).columns

Traning

In [35]:
from sklearn.model_selection import train_test_split

# split
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (80088, 28)
X_test: (20022, 28)
y_train: (80088,)
y_test: (20022,)

Applying Model

In [36]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

Prediction

In [37]:
pred = model.predict(X_test)

print(pred[:10])

[18375.14 47655.45 30142.68 94090.73 79667.15 21795.11 15116.21 24982.08
 30896.46 30014.24]

Accuracy

In [38]:
from sklearn.metrics import mean_absolute_error, r2_score

mae = mean_absolute_error(y_test, pred)
r2 = r2_score(y_test, pred)

print("MAE:", mae)
print("R2 Score:", r2)

MAE: 2198.9050264708817
R2 Score: 0.9877222163717666

In [39]:
import joblib
joblib.dump(model, "mobile_price_prediction.pkl")

['mobile_price_prediction.pkl']